services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: produto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  produto-service:
    build:
      context: ./back-end/produtos
    container_name: produto-service
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/produto_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8081:8080"   # host:container

  estoque-service:
    build:
      context: ./back-end/estoque
    container_name: estoque-service
    depends_on:
      - produto-service
    environment:
      SERVICOA_URL: http://produto-service:8081/api/produtos
    ports:
      - "8082:8080"  # host:container

volumes:
  postgres_data:
